name: Pull Request Actions
on: [pull_request]
jobs:
  test:
    name: Build and Test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - run: yarn test
